# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'e P ONE For iPad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!



  # Pods for e P ONE For iPad

  target 'e P ONE For iPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'e P ONE For iPadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
